spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 826226269274-a81pir03hqsstacc9te6rq55l5k58ern.apps.googleusercontent.com
            client-secret : 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
            scope:
              - profile
              - email # -openid(default) 명시 안한 이유-> openId Provider 구현이 필요하기때문에 # - 하나의 OAuth2Service 로 사용하기위해
          naver:
            client-name: Naver
            client-id : A7Idf_5t6xwuTHLYAV3S
            client-secret : LySqepVZRg
            redirect-uri : "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response