spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQL55Dialect
#    open-in-view: false
  h2:
    console:
      enabled: true
  application-oauth:
    yml:
  profiles:
    include: oauth
#  mustache:
#    suffix: mustache
#    prefix: classpath:/templates


