spring:
  datasource:
#    url: jdbc:h2:mem:test
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        storage_engine: innodb
    open-in-view: false
  h2:
    console:
      enabled: true
  application-oauth:
    yml:
  profiles:
    include: oauth
  session:
    store-type: jdbc
#  mustache:
#    suffix: mustache
#    prefix: classpath:/templates


